
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A_CLOSE A_OPEN IMGhtml : elementoselementos : elemento elementos\n                 | elementoelemento : link\n                | imagelink : A_OPEN A_CLOSEimage : IMG'
    
_lr_action_items = {'A_OPEN':([0,3,4,5,7,9,],[6,6,-4,-5,-7,-6,]),'IMG':([0,3,4,5,7,9,],[7,7,-4,-5,-7,-6,]),'$end':([1,2,3,4,5,7,8,9,],[0,-1,-3,-4,-5,-7,-2,-6,]),'A_CLOSE':([6,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'html':([0,],[1,]),'elementos':([0,3,],[2,8,]),'elemento':([0,3,],[3,3,]),'link':([0,3,],[4,4,]),'image':([0,3,],[5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> html","S'",1,None,None,None),
  ('html -> elementos','html',1,'p_html','parser.py',9),
  ('elementos -> elemento elementos','elementos',2,'p_elementos','parser.py',14),
  ('elementos -> elemento','elementos',1,'p_elementos','parser.py',15),
  ('elemento -> link','elemento',1,'p_elemento','parser.py',20),
  ('elemento -> image','elemento',1,'p_elemento','parser.py',21),
  ('link -> A_OPEN A_CLOSE','link',2,'p_link','parser.py',26),
  ('image -> IMG','image',1,'p_image','parser.py',35),
]
