
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRIR_ETIQUETA CERRAR_ETIQUETA ETIQUETA_AUTOCIERRE FIN_ETIQUETA IGUAL NOMBRE_ATRIBUTO TEXTO VALOR_ATRIBUTOhtml : elementoselementos : elemento elementos\n                 | elementoelemento : ABRIR_ETIQUETA atributos FIN_ETIQUETA elementos CERRAR_ETIQUETAelemento : ETIQUETA_AUTOCIERREelemento : TEXTOatributos : atributo atributos\n                 | atributo\n                 | atributo : NOMBRE_ATRIBUTO IGUAL VALOR_ATRIBUTO'
    
_lr_action_items = {'ABRIR_ETIQUETA':([0,3,5,6,11,16,],[4,4,-5,-6,4,-4,]),'ETIQUETA_AUTOCIERRE':([0,3,5,6,11,16,],[5,5,-5,-6,5,-4,]),'TEXTO':([0,3,5,6,11,16,],[6,6,-5,-6,6,-4,]),'$end':([1,2,3,5,6,7,16,],[0,-1,-3,-5,-6,-2,-4,]),'CERRAR_ETIQUETA':([3,5,6,7,14,16,],[-3,-5,-6,-2,16,-4,]),'FIN_ETIQUETA':([4,8,9,12,15,],[-9,11,-8,-7,-10,]),'NOMBRE_ATRIBUTO':([4,9,15,],[10,10,-10,]),'IGUAL':([10,],[13,]),'VALOR_ATRIBUTO':([13,],[15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'html':([0,],[1,]),'elementos':([0,3,11,],[2,7,14,]),'elemento':([0,3,11,],[3,3,3,]),'atributos':([4,9,],[8,12,]),'atributo':([4,9,],[9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> html","S'",1,None,None,None),
  ('html -> elementos','html',1,'p_html','parser.py',10),
  ('elementos -> elemento elementos','elementos',2,'p_elementos','parser.py',14),
  ('elementos -> elemento','elementos',1,'p_elementos','parser.py',15),
  ('elemento -> ABRIR_ETIQUETA atributos FIN_ETIQUETA elementos CERRAR_ETIQUETA','elemento',5,'p_elemento_etiqueta_abre','parser.py',19),
  ('elemento -> ETIQUETA_AUTOCIERRE','elemento',1,'p_elemento_autocierre','parser.py',24),
  ('elemento -> TEXTO','elemento',1,'p_elemento_texto','parser.py',29),
  ('atributos -> atributo atributos','atributos',2,'p_atributos','parser.py',33),
  ('atributos -> atributo','atributos',1,'p_atributos','parser.py',34),
  ('atributos -> <empty>','atributos',0,'p_atributos','parser.py',35),
  ('atributo -> NOMBRE_ATRIBUTO IGUAL VALOR_ATRIBUTO','atributo',3,'p_atributo','parser.py',39),
]
